export default {
  LOGIN : "Login",
  EMPTY_EMAIL : "Email can't be empty.",
  VALID_EMAIL : 'Ooops! We need a valid email address.',
  EMPTY_PASSWORD : "Password can't be empty.",
  VALID_PASSWORD : 'Password must be at least 5 characters long.',
  WELCOME_BACK : "Welcome back.",
  ENTER_PASSWORD : "Enter Password",
  ENTER_EMAIL : "Enter Email",
  LOGIN : "LOGIN",
  WRONG_PASSWORD : "Incorrect Password",
  WRONG_EMAIL : "Incorrect Email",
  BACK : "Back",
  RESTAURANT_LIST : "Restaurant List",
  EXIT : "Exit",
  EXIT_TITLE : "Are you sure you want to go back?",
  CANCEL : "Cancel",
  YES : "Yes",
  MAP_VIEW : "Map View"
};
